name: ArgoCD - Staging Tags CI

on:
  pull_request:
    types:
      - closed
jobs:
  update-tags:
    uses: GlueOps/github-workflows/.github/workflows/argocd-tags-ci.yml@main
    if: github.event.pull_request.merged == true
    secrets:
      GH_TOKEN: ${{ secrets.DOC_TOKEN }}
    with:
      STACK_REPO: 'https://github.com/venkata-tenant-test-1/deployment-configurations'
      ENV: 'stage'
      CREATE_PR: false
